import SwiftUI
import CleanupCore
import CleanupScan

// Deletion preview + confirmation + results (M2). The preview is a dry run:
// nothing is removed until the tier-appropriate confirmation is satisfied.

struct PlanPreviewSheet: View {
    let model: ScanModel
    @State private var typed = ""

    private var plan: DeletionPlan { model.plan ?? DeletionPlan(items: [], refused: [], mode: .trash) }

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Review deletion").font(.title3.bold())

            Picker("", selection: Binding(get: { model.mode }, set: { model.updateMode($0) })) {
                Text("Move to Trash (reversible)").tag(DeletionMode.trash)
                Text("Delete permanently").tag(DeletionMode.permanent)
            }
            .pickerStyle(.segmented)

            HStack {
                Text("Reclaims \(formatBytes(plan.reclaimableTotal))").bold()
                Spacer()
                Text("\(plan.items.count) item(s)").foregroundStyle(.secondary)
            }

            // per-tier breakdown
            HStack(spacing: 12) {
                ForEach(SafetyTier.allCases, id: \.self) { tier in
                    if let bytes = plan.perTierTotals[tier] {
                        HStack(spacing: 4) {
                            RoundedRectangle(cornerRadius: 2).fill(tier.color).frame(width: 9, height: 9)
                            Text("\(tier.label): \(formatBytes(bytes))").font(.caption2)
                        }
                    }
                }
            }

            List {
                Section("Will be removed") {
                    ForEach(plan.items, id: \.path) { item in
                        HStack {
                            Image(systemName: "circle.fill").foregroundStyle(item.tier.color).font(.caption2)
                            Text(item.path).font(.caption.monospaced()).lineLimit(1).truncationMode(.middle)
                            Spacer()
                            Text(formatBytes(item.allocatedSize)).font(.caption).foregroundStyle(.secondary)
                        }
                    }
                }
                if !plan.refused.isEmpty {
                    Section("Refused (protected — never removed)") {
                        ForEach(plan.refused, id: \.path) { r in
                            VStack(alignment: .leading) {
                                Text(r.path).font(.caption.monospaced()).lineLimit(1)
                                Text(r.reason).font(.caption2).foregroundStyle(.secondary)
                            }
                        }
                    }
                }
            }
            .frame(minHeight: 180)

            confirmation
        }
        .padding(18)
        .frame(width: 560, height: 460)
    }

    @ViewBuilder
    private var confirmation: some View {
        let level = model.requiredConfirmation
        VStack(alignment: .leading, spacing: 8) {
            switch level {
            case .warning:
                Label("These caches will be regenerated by their apps as needed.",
                      systemImage: "info.circle").font(.caption).foregroundStyle(.secondary)
            case .typeToConfirm:
                Label("This removes risky or tool-managed data. Type DELETE to confirm.",
                      systemImage: "exclamationmark.triangle").font(.caption).foregroundStyle(.orange)
                TextField("Type DELETE", text: $typed).textFieldStyle(.roundedBorder).frame(width: 200)
            case .simple, .none:
                EmptyView()
            }

            HStack {
                Button("Cancel") { model.showingPlan = false }
                Spacer()
                Button(model.mode == .permanent ? "Delete Permanently" : "Move to Trash") {
                    Task { await model.executePlan() }
                }
                .keyboardShortcut(.defaultAction)
                .disabled(!canConfirm(level))
                .tint(model.mode == .permanent ? .red : .accentColor)
            }
        }
    }

    private func canConfirm(_ level: ConfirmationLevel) -> Bool {
        guard !plan.isEmpty else { return false }
        if level == .typeToConfirm { return typed == "DELETE" }
        return true
    }
}

struct ResultsSheet: View {
    let model: ScanModel

    private var results: [DeletionExecutor.ItemResult] { model.results ?? [] }

    private func count(_ predicate: (DeletionExecutor.Outcome) -> Bool) -> Int {
        results.filter { predicate($0.outcome) }.count
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Deletion complete").font(.title3.bold())
            HStack(spacing: 16) {
                summary("Trashed", count { $0 == .trashed }, .green)
                summary("Deleted", count { $0 == .deleted }, .blue)
                summary("Failed", count { if case .failed = $0 { return true }; return false }, .orange)
                summary("Refused", count { if case .refused = $0 { return true }; return false }, .red)
            }
            List(results, id: \.path) { r in
                HStack {
                    Text(r.path).font(.caption.monospaced()).lineLimit(1).truncationMode(.middle)
                    Spacer()
                    Text(label(r.outcome)).font(.caption2).foregroundStyle(.secondary)
                }
            }
            .frame(minHeight: 160)
            HStack {
                Spacer()
                Button("Done") { model.showingResults = false }.keyboardShortcut(.defaultAction)
            }
        }
        .padding(18)
        .frame(width: 520, height: 380)
    }

    private func summary(_ label: String, _ n: Int, _ color: Color) -> some View {
        VStack {
            Text("\(n)").font(.title2.bold()).foregroundStyle(color)
            Text(label).font(.caption2).foregroundStyle(.secondary)
        }
    }

    private func label(_ outcome: DeletionExecutor.Outcome) -> String {
        switch outcome {
        case .trashed: return "trashed"
        case .deleted: return "deleted"
        case .failed(let r): return "failed — \(r)"
        case .refused(let r): return "refused — \(r)"
        }
    }
}
